application: githubbadge
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?samples/.*

handlers:
- url: /
  script: main.application

- url: /badge/(.*)
  script: main.application

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /image/(.*\.(gif|png|jpg))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg))

- url: /crossdomain.xml 
  mime_type: text/xml
  static_files: static/xml/crossdomain.xml 
  upload: static/xml/crossdomain.xml 
