application: githubbadge
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?samples/.*

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /
  script: main.py

- url: /badge/(.*)
  script: main.py

- url: /stats
  script: main.py

- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js

- url: /image/(.*\.(gif|png|jpg))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg))

admin_console:
  pages:
  - name: My Console
    url: /admin/interactive
  - name: My Memcache
    url: /admin/memcache
  - name: My XMPP
    url: /admin/xmpp
  - name: My Inbound Mail
    url: /admin/inboundmail
