application: githubbadge
version: 2-test
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?samples/.*

handlers:
- url: /
  script: main.application

- url: /badge/(.*)
  script: main.application

- url: /stats
  script: main.application

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /image/(.*\.(gif|png|jpg))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg))

admin_console:
  pages:
  - name: My Console
    url: /admin/interactive
  - name: My Memcache
    url: /admin/memcache
  - name: My XMPP
    url: /admin/xmpp
  - name: My Inbound Mail
    url: /admin/inboundmail
